"""alter the col name of the car_name field in the cars table to name

Revision ID: b8e40811527c
Revises: 71d89889f956
Create Date: 2024-04-26 21:52:42.748593

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b8e40811527c'
down_revision = '71d89889f956'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=False))
        batch_op.drop_column('car_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('car_name', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
